on: workflow_call

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: {{ secrets.GOOGLE_ACCOUNT_CREDENTIALS }}

      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: 'nieko3/f1api:latest'
          service: {{ secrets.GOOGLE_PROJECT_ID }}